### ISSUE TITLE
Implementation of Analytic Non-interactive gaussian

### ISSUE THREAD

**Issue by copperwire** [copperwire/comp_phys_2#3]
We had this implementation in the previous code (`main.cpp` in the `src` dir). Should be pretty straightforward to implement. 

Note that the energy should go as 
<a href="https://www.codecogs.com/eqnedit.php?latex=\frac{E_l}{N_p}&space;=&space;0.5\times&space;N_d" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\frac{E_l}{N_p}&space;=&space;0.5\times&space;N_d" title="\frac{E_l}{N_p} = 0.5\times N_d" /></a>
Where the variable N denotes the "number of" particles and dimensions for the respective sub indices p and d.

**Comment by copperwire** [comment]
I belive the energy goes as above for <a href="https://www.codecogs.com/eqnedit.php?latex=\alpha&space;=&space;1" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\alpha&space;=&space;1" title="\alpha = 1" /></a>

**Comment by copperwire** [comment]
I was mistaken, this is the case for <a href="https://www.codecogs.com/eqnedit.php?latex=\alpha&space;=&space;0.5" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\alpha&space;=&space;0.5" title="\alpha = 0.5" /></a>

**Comment by KariEriksen** [comment]
Yeah! Your right of course. We haven't implemented steepest decent yet!
